POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title":"test7",
    "author":"you",
    "ulr":"www.blogs.fi/my_blog1",
    "likes":6
}

###

DELETE http://localhost:3003/api/blogs/6a63ca9d87f3d795b26f6026
###
GET http://localhost:3003/api/blogs

###
PUT http://localhost:3003/api/blogs/6a63a4b9eb3f2fc850e180ec HTTP/1.1
Content-Type: application/json

{
  "title": "Learning REST Client",
  "author": "John Smith",
  "url": "https://example.com/blog",
  "likes": 42
}

###

GET http://127.0.0.1:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5CI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RpS8OkeXR0w6Rqw6QiLCJpZCI6IjZhNzJmNmMyMGZjYTczOTNkYmQ1YzRhNiIsImlhdCI6MTc4NTkyMTczOH0._MfTEoJzWnxgC2lM9on0-89MKYjhcq_ITRPAYCaLpsk

{
  "title": "Local test3",
  "author": "Sami",
  "url": "http://example.com",
  "likes": 5
}

###
PUT http://localhost:3003/api/blogs/6a72f7987e0b48938f48e076
Content-Type: application/json

{
  "title": "Nimi muuttui",
  "author": "Sami",
  "url": "http://example.com",
  "likes": 5
}
###
GET http://127.0.0.1:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "TestiKäyttäjä",
  "name": "Tepa",
  "password": "salana"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{  
  "username": "TestiKäyttäjä",
  "password": "salana"
}