GET http://localhost:3001/api/persons
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/4
###
DELETE http://localhost:3001/api/persons/5
###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Benedict Cumberbatch",
    "number": "040-434754"
}
###
GET https://fullstack2026-z0do.onrender.com/api/persons
###
GET https://fullstack2026-z0do.onrender.com/info
###
GET https://fullstack2026-z0do.onrender.com/api/persons/4
###
DELETE https://fullstack2026-z0do.onrender.com/api/persons/5729
###
POST https://fullstack2026-z0do.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Benedict Cumberbatch",
    "number": "040-434754"
}